services:
  - type: web
    name: my-react-app
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    headers:
      - source: /**
        headers:
          - key: Cache-Control
            value: public, max-age=0, must-revalidate
    redirects:
      - source: /*
        destination: /index.html
        status: 200
